#!/usr/bin/env python3
"""
Generate reusable one-pair Gaussian coefficients for scheduled center zmm slots.

The emitted table is experimental: each selected 16-lane zmm slot gets one
linear pair z ~= c1*x + c0 fitted across the tested post-skip Sobol blocks.
Unselected slots keep placeholder coefficients and must use the normal table.
"""

import argparse
from pathlib import Path

import numpy as np
from scipy.special import ndtri

import generate_gaussian_coeffs as gg


LANES = 16
ZMM_SLOTS = gg.WORK_CHUNK_SIZE // LANES
MANTISSA_ONE = 0x3f800000


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser()
    ap.add_argument("--blocks", type=int, default=128)
    ap.add_argument("--skip-values", type=int, default=8192)
    ap.add_argument("--target", type=float, default=1.0e-5)
    ap.add_argument("--out", type=Path, default=Path("private/gaussian_center_shared_coeff_values_2048.h"))
    return ap.parse_args()


def raw_x_from_u(u: np.ndarray) -> np.ndarray:
    shifted = (np.asarray(u, dtype=np.float64) * (1 << 23)).astype(np.uint32)
    bits = shifted | np.uint32(MANTISSA_ONE)
    return bits.view(np.float32).astype(np.float64)


def fit_shared(x: np.ndarray, y: np.ndarray) -> tuple[float, float, float]:
    n = float(x.size)
    sx = float(np.sum(x))
    sy = float(np.sum(y))
    sxx = float(np.sum(x * x))
    sxy = float(np.sum(x * y))
    den = n * sxx - sx * sx
    if abs(den) < 1.0e-30:
        c1 = 0.0
        c0 = sy / n
    else:
        c1 = (n * sxy - sx * sy) / den
        c0 = (sy - c1 * sx) / n
    err = float(np.max(np.abs(c1 * x + c0 - y)))
    return c1, c0, err


def fmt_f32(value: float) -> str:
    return f"{np.float32(value).item():.9g}f"


def main() -> None:
    args = parse_args()
    block, mem_idx, _logical, u = gg.scheduled_values(args.skip_values, gg.SOBOL_BLOCK_SIZE, args.blocks)
    del block
    x = raw_x_from_u(u)
    z = ndtri(u)
    slot = (mem_idx % gg.WORK_CHUNK_SIZE) // LANES

    c0 = np.zeros(ZMM_SLOTS, dtype=np.float32)
    c1 = np.zeros(ZMM_SLOTS, dtype=np.float32)
    err = np.full(ZMM_SLOTS, np.inf, dtype=np.float64)
    selected = np.zeros(ZMM_SLOTS, dtype=np.uint32)

    for slot_id in range(ZMM_SLOTS):
        mask = slot == slot_id
        fit_c1, fit_c0, fit_err = fit_shared(x[mask], z[mask])
        c0[slot_id] = np.float32(fit_c0)
        c1[slot_id] = np.float32(fit_c1)
        err[slot_id] = fit_err
        selected[slot_id] = 1 if fit_err <= args.target else 0

    selected_slots = [i for i, flag in enumerate(selected) if flag]
    pair_aligned = all((s ^ 1) in selected_slots for s in selected_slots)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="ascii") as f:
        f.write("/* Generated by generate_center_shared_coeffs.py. Experimental one-pair center zmm coefficients. */\n")
        f.write("#ifndef GAUSSIAN_CENTER_SHARED_COEFF_VALUES_2048_H\n")
        f.write("#define GAUSSIAN_CENTER_SHARED_COEFF_VALUES_2048_H\n\n")
        f.write(f"#define GAUSS_CENTER_SHARED_TARGET {args.target:.9g}f\n")
        f.write(f"#define GAUSS_CENTER_SHARED_BLOCKS {args.blocks}u\n")
        f.write(f"#define GAUSS_CENTER_SHARED_ZMM_SLOTS {ZMM_SLOTS}u\n")
        f.write(f"#define GAUSS_CENTER_SHARED_SELECTED {len(selected_slots)}u\n")
        f.write(f"#define GAUSS_CENTER_SHARED_ZMM_PER_8192_BLOCK {2 * len(selected_slots)}u\n")
        f.write(f"#define GAUSS_CENTER_SHARED_PAIR_ALIGNED {1 if pair_aligned else 0}u\n\n")

        for name, arr in (
            ("gauss_center_shared_selected", selected),
        ):
            f.write(f"static const uint32_t {name}[{ZMM_SLOTS}] __attribute__((aligned(64))) = {{\n")
            for i in range(0, ZMM_SLOTS, 16):
                f.write("    " + ", ".join(f"{int(v)}u" for v in arr[i:i + 16]) + ",\n")
            f.write("};\n\n")

        for name, arr in (
            ("gauss_center_shared_c0", c0),
            ("gauss_center_shared_c1", c1),
        ):
            f.write(f"static const float {name}[{ZMM_SLOTS}] __attribute__((aligned(64))) = {{\n")
            for i in range(0, ZMM_SLOTS, 8):
                f.write("    " + ", ".join(fmt_f32(v) for v in arr[i:i + 8]) + ",\n")
            f.write("};\n\n")

        f.write("static const float gauss_center_shared_max_abs_z_error[GAUSS_CENTER_SHARED_ZMM_SLOTS] __attribute__((aligned(64))) = {\n")
        for i in range(0, ZMM_SLOTS, 8):
            f.write("    " + ", ".join(fmt_f32(v if np.isfinite(v) else 0.0) for v in err[i:i + 8]) + ",\n")
        f.write("};\n\n")
        f.write("#endif\n")

    print(f"target              : {args.target:.9g}")
    print(f"blocks              : {args.blocks}")
    print(f"selected slots      : {len(selected_slots)} / {ZMM_SLOTS}")
    print(f"zmm per 8192 block  : {2 * len(selected_slots)} / 512")
    print(f"pair aligned        : {int(pair_aligned)}")
    print(f"worst selected err  : {max(err[selected.astype(bool)]):.12g}" if selected_slots else "worst selected err  : n/a")
    print(f"selected slots      : {' '.join(str(s) for s in selected_slots)}")
    print(f"wrote               : {args.out}")


if __name__ == "__main__":
    main()
